# HTML
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 branches:
  include:
    - release/*
    - develop
  exclude:
    - master

pool:
  vmImage: ubuntu-latest

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.sourcesDirectory)'
    includeRootFolder: false

# Archive the files
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(agent.builddirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

# Copy zip file to 'source' folder
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(agent.builddirectory)'
    Contents: '*.zip'
    TargetFolder: '/source'
    CleanTargetFolder: true
    OverWrite: true

# Publish artefacts
- task: PublishBuildArtifacts@1
