# HTML
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 branches:
  include:
    - release/*
    - develop
  exclude:
    - master

pool:
  vmImage: ubuntu-latest

steps:

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(build.sourcesDirectory)/s'
    Contents: '**'
    TargetFolder: '$(build.sourcesDirectory)/Arch.zip'
    OverWrite: true

- task: ZipDirectory@1
  inputs:
    ItemSpec: '$(build.sourcesDirectory)/s'

# Archive the files
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.sourcesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/Build.zip'
    replaceExistingArchive: true
    verbose: true

# Publish artefacts
- task: PublishBuildArtifacts@1