# HTML
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 branches:
  include:
    - release/*
    - develop
  exclude:
    - master

pool:
  vmImage: ubuntu-latest

steps:

# Archive the files
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.sourcesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/Build.zip'
    replaceExistingArchive: true

# Publish artefacts
- task: PublishBuildArtifacts@1
